### ISSUE TITLE
[Motocycle mechanical integration]. Issues to resolve for mechanical integration.

### ISSUE THREAD

**Issue by francisjjp** [Sinapse-Energia/Torrot-EC-M2M#17]
Some issues must be resolved to integrate 5 motocycles with their sensors (quality air meter,  level sound meter, iot hub sinapse).

They are uploaded two report file regarding the complete integration. One SINAPSE report and another one provided from TORROT.

**Comment by sinapseenergia** [comment]
This kind of issues and works , doesn´t belongs here.

GitHub platform it´s just for FW development
